CH.SC.U4CSE24110 LINEAR REGRESSION EXERCISE 2

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
data = pd.DataFrame({
    'Weight': [79, 69, 73, 95, 82, 55, 69, 71, 64, 69],
    'Height': [1.80, 1.68, 1.82, 1.70, 1.87, 1.55, 1.50, 1.78, 1.67, 1.64],
    'Age': [35, 39, 25, 60, 27, 18, 89, 42, 16, 52],
    'Gender': ['Male', 'Male', 'Male', 'Male', 'Male',
               'Female', 'Female', 'Female', 'Female', 'Female']
})

In [3]:
data.head()

   Weight  Height  Age Gender
0      79    1.80   35   Male
1      69    1.68   39   Male
2      73    1.82   25   Male
3      95    1.70   60   Male
4      82    1.87   27   Male

In [4]:
data.shape

(10, 4)

In [5]:
data['Gender_Male'] = data['Gender'].map({'Male': 1, 'Female': 0})

In [6]:
data.head()

   Weight  Height  Age Gender  Gender_Male
0      79    1.80   35   Male            1
1      69    1.68   39   Male            1
2      73    1.82   25   Male            1
3      95    1.70   60   Male            1
4      82    1.87   27   Male            1

In [7]:
X = data[['Height', 'Age', 'Gender_Male']]
y = data['Weight']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [9]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [10]:
predictions = model.predict(X_test)

In [11]:
print("Actual vs Predicted Weights")
print("---------------------------")

comparison = pd.DataFrame({
    'Actual Weight': y_test.values,
    'Predicted Weight': predictions
})

print(comparison)

Actual vs Predicted Weights
---------------------------
   Actual Weight  Predicted Weight
0             64         56.856510
1             69         79.105761

In [12]:
mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("Regression Evaluation Metrics")
print("-----------------------------")
print(f"Mean Absolute Error (MAE): {mae:.6f}")
print(f"Mean Squared Error (MSE): {mse:.6f}")
print(f"R-squared Score (R2): {r2:.6f}")

Regression Evaluation Metrics
-----------------------------
Mean Absolute Error (MAE): 8.624625
Mean Squared Error (MSE): 76.577927
R-squared Score (R2): -11.252468

In [13]:
print("Regression Equation:")
print(f"Weight = {model.intercept_:.4f} + "
      f"{model.coef_[0]:.4f}(Height) + "
      f"{model.coef_[1]:.4f}(Age) + "
      f"{model.coef_[2]:.4f}(Gender)")

Regression Equation:
Weight = -3.0552 + 32.8353(Height) + 0.3173(Age) + 14.6231(Gender)

In [15]:
new_person = pd.DataFrame({
    'Height': [1.75],
    'Age': [30],
    'Gender_Male': [1]
})

predicted_weight = model.predict(new_person)

print("Predicted Weight:", predicted_weight[0])

Predicted Weight: 78.548582018849